# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-24 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
    ]
